// <auto-generated />
namespace SSE_Reporting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class levelidaddedtopositionclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(levelidaddedtopositionclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201905121115405_levelid added to position class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
